<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net9.0-windows</TargetFramework>
		<OutputType>WinExe</OutputType>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<UseWindowsForms>true</UseWindowsForms>
		<ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
		<NoWarn>CA1416</NoWarn>
		<ApplicationIcon>res\weather-icon.ico</ApplicationIcon>
		<Version>0.4.0</Version>
	</PropertyGroup>
	<ItemGroup>
		<Content Include="appsettings.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="res\weather-icon.ico" />
		<PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
		<PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="9.0.7" />
		<PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.7" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.7" />
		<PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="9.0.7" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.7" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.7" />
		<PackageReference Include="Microsoft.Extensions.FileProviders.Abstractions" Version="9.0.7" />
		<PackageReference Include="Microsoft.Extensions.FileProviders.Physical" Version="9.0.7" />
		<PackageReference Include="Microsoft.Extensions.FileSystemGlobbing" Version="9.0.7" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.7" />
		<PackageReference Include="Microsoft.Extensions.Http" Version="9.0.7" />
		<PackageReference Include="Microsoft.Extensions.Primitives" Version="9.0.7" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
		<PackageReference Include="System.IO.Pipelines" Version="9.0.7" />
		<PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.1.2" />
		<PackageReference Include="System.Text.Encodings.Web" Version="9.0.7" />
		<PackageReference Include="System.Text.Json" Version="9.0.7" />
	</ItemGroup>
</Project>